site_name: Análise da Eficiência do Sono - Hypnos Data
site_description: Projeto de Data Science para análise e predição da eficiência do sono
site_author: Squad 11 - Alan, Ayrton, Cauan, Hosana

plugins:
  - search

theme:
  name: material
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/bed
  palette:
    - scheme: default
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb
        name: Alternar para modo escuro
    - scheme: slate
      primary: teal
      accent: teal
      toggle:
        icon: material/lightbulb-outline
        name: Alternar para modo claro
  features:
    - navigation.tabs
    - navigation.top
    - navigation.expand
    - navigation.tabs.sticky
    - navigation.tracking
    - content.code.copy
    - content.code.annotate

markdown_extensions:
  - footnotes
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.keys
  - tables
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - assets/js/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.number.min.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/sorts/tablesort.date.min.js

extra_css:
  - assets/css/tables.css

# Repository
repo_name: hypnos-data
repo_url: https://github.com/Alan-oliveir/hypnos-data

# Navegação
nav:
  - Home: index.md
  - Dataset: dataset.md
  - Análise Exploratória: eda.md
  - Pré-processamento: preprocessing.md
  - Modelagem: modeling.md
  - Resultados: results.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Alan-oliveir/hypnos-data
      name: Repositório no GitHub